import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, { useState, useRef, useEffect } from "react"
import Header from './Header'
import Profile from './Profile'
import Code from './code.json';
import Contents from './Contents'
import styles from '../styles/Home.module.css'

const proptitle = 'TK PORTFOLIO';


export default function Home() {
  const [open, setOpen] = useState(true)


  const [switchImg, setSwitchImg] = useState(0);
  const setImgEvent = (e) => {
    // console.log(e.currentTarget.getAttribute('data'));
    const ImgNum = e.currentTarget.getAttribute('data')
    setSwitchImg(ImgNum)
    console.log(switchImg)

  }

  const el = useRef(null);
  useEffect(() => {
    console.log(el.current);
    console.log(el.current.innerHTML);
    setOpen(!open)
  }, [switchImg]);

  return (
    <div className={styles.container}>
      <Head>
        <title>{proptitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className={styles.imgwrap}>
        <Link href="/"><h1 className={styles.FVTitle}>TOSHIYUKI<span></span>KIMURA<span></span>PORTFOLIO</h1></Link>
        <Image src="/SVG/topimg.svg" className={styles.topimg} alt="TOP" layout='fill' objectFit='cover' />
      </div>

      <section className={styles.gdSection} style={{backgroundSize:'800px'}}>
      <div style={{ height: '70px' }}></div>

      <h3 className={styles.wdTitle}>WEB DESIGN<span>ウェブデザイン</span></h3>

      <div className={styles.grid} ref={el} >
        <div className={styles.gridInner}>
          <figure className={styles.wdFigure}>
            <div className={`${styles.wdImg} ${open ? styles.isImgOpen : styles.isImgClose }`}><img src={Code.wd[switchImg].image} alt="" width="100%" /></div>
            <div className={styles.wdDescription}>
              <span>{Code.wd[switchImg].year}</span>
              <p>{Code.wd[switchImg].display}</p>
              <p>{Code.wd[switchImg].descript}</p>
            </div>
          </figure>
          <div className={styles.wdChildgrid}>
            <p><span className={`${open ? styles.isOpen : styles.isClose }`}><img src={Code.wd[switchImg].bodyimage1} alt="" /></span></p>
            <p><span className={`${open ? styles.isOpen : styles.isClose }`}><img src={Code.wd[switchImg].bodyimage2} alt="" /></span></p>
            <p><span className={`${open ? styles.isOpen : styles.isClose }`}><img src={Code.wd[switchImg].bodyimage3} alt="" /></span></p>
            <p><span className={`${open ? styles.isOpen : styles.isClose }`}><img src={Code.wd[switchImg].bodyimageSP1} alt="" /></span></p>
            <p><span className={`${open ? styles.isOpen : styles.isClose }`}><img src={Code.wd[switchImg].bodyimageSP2} alt="" /></span></p></div>
        </div>
        <div className={styles.gridSide}>
          <ul>
            {
              Code.wd.map((el, i) =>
                <Link href={el.path}><li onMouseEnter={setImgEvent} data={i} >{el.display}</li></Link>
              )
            }
          </ul>
        </div>
      </div>
      </section>

      <section className={styles.gdSection}>
        <div style={{ height: '120px' }}></div>
        <h3 className={styles.wdTitle}>GRAPHIC DESIGN<span>グラフィックデザイン</span></h3>
        <div className={styles.grGrid}>
          <div className={styles.grImg}><div className={styles.grImgInner}><img src="images/wateras.jpg" alt="" className={styles.GRimg} /></div></div>
          <div className={styles.grDescript}>{Code.gd[0].display}</div>
          <div className={styles.grSide}>
            <ul>
            {
              Code.gd.map((el, i) =>
                <Link href={el.path}><li onMouseEnter={setImgEvent} data={i} >{el.display}<span style={{display: 'inline-block'}}>{el.year}</span></li></Link>
              )
            }
            </ul>
          </div>
        </div>
      </section>

      <section className={styles.prgSection}>
        <div style={{ height: '120px' }}></div>
        <h3 className={styles.wdTitle}>PROGRAMING<span>プログラミング</span></h3>
        <div className={styles.prColm}>
          <p>Dialogflow Chatbot<br /><br />GoogleSpreadSheet Api<br /><br />JsonServerのモックAPIをNext.jsで扱う</p>
        </div>
      </section>

      <h3 className={styles.wdTitle}>ANALOG<span>アナログ</span></h3>
      <div className={styles.anlgColm}>

      </div>

      <Profile />



      <footer className={styles.footer}>
        <span className={styles.logo}>
        </span>
      </footer>
    </div>
  )
}
